# Generated by Django 4.1.13 on 2026-01-29 05:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richtextpage',
            name='body',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock()), ('show', wagtail.blocks.BooleanBlock(default=True, label='Show', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
